server:
  port: 9011

spring:
  application:
    name: tensquare-manager

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: zuul.com
    prefer-ip-address: true

jwt:
  config:
    key: itcast


zuul:
  routes:
    tensqure-base:
      path: /base/**
      serviceId: tensqure-base
    tensqure-user:
      path: /user/**
      serviceId: tensqure-user
    tensqure-qa:
      path: /qa/**
      serviceId: tensqure-qa

