server:
  port: 9012

spring:
  application:
    name: tensquare-web

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
   # instance-id:
    prefer-ip-address: true


zuul:
  routes:
    tensqure-base:
      path: /base/**
      serviceId: tensqure-base
    tensqure-user:
      path: /user/**
      serviceId: tensqure-user
    tensqure-qa:
      path: /qa/**
      serviceId: tensqure-qa

