server: 
  port: 9008
spring: 
  application:  
    name: tensquare-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tensquare_user?characterEncoding=UTF8
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: 192.168.217.130
  rabbitmq:
    host: 192.168.217.130
    port: 5672
    username: guest
    password: guest
  security:
    oauth2:
      resourceserver

jwt:
  config:
    key: itcast
    ttl: 6000000
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka/
    instance:
      # instance-id: payment8001
      prefer-ip-address: true



